- name: Retrieve packages for repository
  shell: |
    curl -L -O \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer {{ bearer_token }}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://maven.pkg.github.com/{{ repository_owner }}/{{ repository_name }}/com/com.mycompany.app/vprofile/Latest/vprofile-0.1.2.war
