- name: Download Maven Package from GitHub Packages 
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
