- name: Download Maven Package from GitHub Packages 
  hosts: 192.168.1.10
  become: true
  gather_facts: true
  tasks:
    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /opt/apache-tomcat-9.0.85.tar.gz
        force: true
        
