---
- name: Download Maven Package from GitHub Packages 
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    bearer_token: secrets.GITHP_TOKEN
    repository_name: hprofile
    repository_owner: ythrinathareddy
    tomcat_home: "/opt/tomcat"
  tasks:
 
    - name: Retrieve packages for repository
      shell: |
            curl -L -O /opt/tomcat/apache-tomcat-9.0.85/webapps/vprofile-0.1.2.war \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer {{ bearer_token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://maven.pkg.github.com/ythrinathareddy/hprofile/com/com.mycompany.app/vprofile/Latest/vprofile-0.1.2.war
      dest: /opt/
      delegate_to: localhost
          
