---
- name: Download Maven Package from GitHub Packages
  hosts: 192.168.1.10
  gather_facts: false
  vars:
      bearer_token: secrets.GITHP_TOKEN 
      repository_name: hprofile
      repository_owner: ythrinathareddy
  tasks:
    - name: Retrieve packages for repository
      get_url:
        url: "https://maven.pkg.github.com/ythrinathareddy/hprofile/com/com.mycompany.app/vprofile/Latest/vprofile-0.1.0.jar"
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ bearer_token }}"
          X-GitHub-Api-Version: "2022-11-28"
        dest: "/opt/vprofile-0.1.0.jar"
